/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programmingassignment2;

// WAN RUI YIN 287456
import java.util.*;
public class BMIForm extends javax.swing.JFrame {

    private int ind;
    private StudentOperation operation;
    private Student stud;
    double weight, height, bmi;
    String status;
     
    public BMIForm() {
        initComponents();
        ind = -1;
        operation = new StudentOperation();
        BMITF.setEditable(false);
        StatusTF.setEditable(false);
        outputTA.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        MatricNoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DegreeRB = new javax.swing.JRadioButton();
        MasterRB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        UniCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        weightTF = new javax.swing.JTextField();
        heightTF = new javax.swing.JTextField();
        BMITF = new javax.swing.JTextField();
        StatusTF = new javax.swing.JTextField();
        CalcButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        DisplayButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator");

        jPanel1.setToolTipText("");

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane1.setViewportView(outputTA);

        jLabel1.setText("Matric Number");

        jLabel3.setText("Name");

        jLabel2.setText("Program  ");

        buttonGroup1.add(DegreeRB);
        DegreeRB.setText("Degree");

        buttonGroup1.add(MasterRB);
        MasterRB.setText("Master");

        jLabel4.setText("University");

        UniCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select your university", "UUM", "USM", "UKM" }));

        jLabel5.setText("Weight (in KG)");

        jLabel6.setText("Height (in CM)");

        jLabel7.setText("BMI");

        jLabel8.setText("Status");

        BMITF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMITFActionPerformed(evt);
            }
        });

        StatusTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTFActionPerformed(evt);
            }
        });

        CalcButton.setText("Calculate BMI");
        CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        DisplayButton.setText("Display All");
        DisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search by Matric no.");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BMITF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StatusTF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DegreeRB)
                                        .addGap(51, 51, 51)
                                        .addComponent(MasterRB))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UniCB, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MatricNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CalcButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DisplayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MatricNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DegreeRB)
                            .addComponent(MasterRB)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UniCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(heightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(BMITF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcButton)
                    .addComponent(SaveButton)
                    .addComponent(ResetButton)
                    .addComponent(DisplayButton)
                    .addComponent(SearchButton)
                    .addComponent(UpdateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcButtonActionPerformed
         BMITF.setEditable(true);
         StatusTF.setEditable(true);
         outputTA.setEditable(true);
        try{
         weight = (double)Integer.parseInt(weightTF.getText());
         height = (double)Integer.parseInt(heightTF.getText());
         if (weight <= 0 || height<=0){
            outputTA.setText("Please enter valid Weight and height.");
            throw new Exception ("Please enter valid weight and height.");
         }
         String bmistring= operation.calculateBMI(weight,height);
         bmi = Double.parseDouble(bmistring);
         status = operation.getStatusbmi(bmi);
         BMITF.setText(bmistring);
         StatusTF.setText(status);
        }
        catch(NumberFormatException e){
             outputTA.setText("Invalid Entry. Please enter digits only.");
         }
         catch(Exception e){
             System.out.println("Error: " + e.getMessage());
         }
    }//GEN-LAST:event_CalcButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        Exception Exception1 = new Exception();
        Exception Exception2 = new Exception();
        outputTA.setEditable(true);
        try{
        int matricnoTFText = Integer.parseInt(MatricNoTF.getText());
        stud= operation.searchRecord(matricnoTFText);
        
         if(stud != null){
            throw new Exception ("Matric Number already entered.");
        }
         
         String nameTFText = NameTF.getText();
         String programText = " ";
        if(DegreeRB.isSelected())
            programText = "Degree";
        if(MasterRB.isSelected())
            programText = "Master";
        String UniCBText = UniCB.getSelectedItem().toString();
        
        weight = Double.parseDouble(weightTF.getText());   
        height = Double.parseDouble(heightTF.getText());      
        bmi = Double.parseDouble(BMITF.getText());
        status = StatusTF.getText();
        
        stud = new Student(matricnoTFText, nameTFText, programText, UniCBText, weight, height, bmi, status);
        operation.saveRecord(++ind,stud);
        outputTA.append("The record has been saved successfully in the array of object.");
 
        }
       
        catch(IndexOutOfBoundsException e){
            outputTA.setText("Please input only 5 student details.");
        }
         catch(Exception e){
            outputTA.setText("Matric Number already entered.\n Please enter a new matric number.");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        MatricNoTF.setText("");
        NameTF.setText("");
        weightTF.setText("");
        heightTF.setText("");
        BMITF.setText("");
        StatusTF.setText("");
        BMITF.setEditable(false);
        StatusTF.setEditable(false);
        UniCB.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        outputTA.setText("");
        outputTA.setEditable(false);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButtonActionPerformed
        outputTA.setEditable(true);
        outputTA.append("  Matric Number          Name          Program     University      Weight     Height     BMI           Status\n");
        for (int i =0; i<=ind+1; i ++)
        outputTA.append((i+1)+".    " + operation.readAllRecord(i) + "\n");
    }//GEN-LAST:event_DisplayButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
       outputTA.setEditable(true);
       int matricnoTFText = Integer.parseInt(MatricNoTF.getText());
       stud= operation.searchRecord(matricnoTFText);
       if (stud == null)
           outputTA.setText("The record is not found.\n");
       else{
            MatricNoTF.setText(String.valueOf(stud.getMatric_number()));
            NameTF.setText(stud.getName());
            weightTF.setText(String.valueOf(stud.getWeight()));
            heightTF.setText(String.valueOf(stud.getHeight()));
            BMITF.setEditable(true);
            StatusTF.setEditable(true);
            BMITF.setText(String.valueOf(stud.getBmi()));
            StatusTF.setText(stud.getStatus());
            if(stud.getProgram().equals("Degree"))
                DegreeRB.setSelected(true);
            else if(stud.getProgram().equals("Master"))
                MasterRB.setSelected(true);
            if(stud.getUniversity().equals("UUM"))
            UniCB.setSelectedIndex(1);
            else if(stud.getUniversity().equals("UKM"))
            UniCB.setSelectedIndex(2);
            else if(stud.getUniversity().equals("USM"))
            UniCB.setSelectedIndex(3);
       }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void BMITFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMITFActionPerformed
 
    }//GEN-LAST:event_BMITFActionPerformed

    private void StatusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTFActionPerformed
      
    }//GEN-LAST:event_StatusTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BMITF;
    private javax.swing.JButton CalcButton;
    private javax.swing.JRadioButton DegreeRB;
    private javax.swing.JButton DisplayButton;
    private javax.swing.JRadioButton MasterRB;
    private javax.swing.JTextField MatricNoTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField StatusTF;
    private javax.swing.JComboBox<String> UniCB;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField heightTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JTextField weightTF;
    // End of variables declaration//GEN-END:variables

}
